// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_sr.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPjmEeaCbABJ9VA3yaS81Vvkvhg8wJmzU',
    appId: '1:105704728102:web:7b1a43456cd8a0157c28e7',
    messagingSenderId: '105704728102',
    projectId: 'rewardsstar-2d8dc',
    authDomain: 'rewardsstar-2d8dc.firebaseapp.com',
    storageBucket: 'rewardsstar-2d8dc.firebasestorage.app',
    measurementId: 'G-0YHVV0CBJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd1bwcDda87hEcpgpePDzvjwNkncTR8n8',
    appId: '1:105704728102:android:cbe51a76c0703cd87c28e7',
    messagingSenderId: '105704728102',
    projectId: 'rewardsstar-2d8dc',
    storageBucket: 'rewardsstar-2d8dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzK_f35-7kcNVynYGIEuAcVe18zg9iqOQ',
    appId: '1:105704728102:ios:c49760f93ef9a0037c28e7',
    messagingSenderId: '105704728102',
    projectId: 'rewardsstar-2d8dc',
    storageBucket: 'rewardsstar-2d8dc.firebasestorage.app',
    iosBundleId: 'com.rewardsstar.au',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzK_f35-7kcNVynYGIEuAcVe18zg9iqOQ',
    appId: '1:105704728102:ios:f2f0762e3115e60d7c28e7',
    messagingSenderId: '105704728102',
    projectId: 'rewardsstar-2d8dc',
    storageBucket: 'rewardsstar-2d8dc.firebasestorage.app',
    iosBundleId: 'com.qapps.qantumApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPjmEeaCbABJ9VA3yaS81Vvkvhg8wJmzU',
    appId: '1:105704728102:web:c3d1b061106c81977c28e7',
    messagingSenderId: '105704728102',
    projectId: 'rewardsstar-2d8dc',
    authDomain: 'rewardsstar-2d8dc.firebaseapp.com',
    storageBucket: 'rewardsstar-2d8dc.firebasestorage.app',
    measurementId: 'G-5M13M3CZYV',
  );

}